"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['run.py']
DATA_FILES = [('high_score.txt')]
OPTIONS = {'iconfile':'assets/gardens.icns',}

setup(
    name="Gardens",
    version="1.0",
    app=APP,
    data_files=DATA_FILES,
    include_package_data=True,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
